### ISSUE TITLE
Program.cs:line 64

### ISSUE THREAD

**Issue by Silver0006** [Perfare/UnityLive2DExtractor#5]
I will be honest I know very little about coding. I wish to rip the live2d files from a game called Mosaique Neko Waifus 4. I have followed the instructions, but keep running into this error and wanted to know if there was a solution.

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at UnityLive2DExtractor.Program.Main(String[] args) in C:\projects\unitylive2dextractor\UnityLive2DExtractor\Program.cs:line 64

I tried opening the file within visual studio, but it detected no errors. I also tried compiling the master branch but received the same error. If you could help that would be greatly appreciated.

**Comment by qinlili23333** [comment]
same problem
